# Introduction to NumPy

In [67]:
import numpy as np
import matplotlib.pyplot as pp

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int64')

In [6]:
a = np.array([1,2,3,4,5], dtype=np.float64)

In [7]:
a.dtype

dtype('float64')

In [8]:
a

array([1., 2., 3., 4., 5.])

In [9]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [14]:
b = np.array([[1,2,3,4], [10,20,30,40], [100,200,300,400]], dtype=np.float64)

In [15]:
b

array([[  1.,   2.,   3.,   4.],
       [ 10.,  20.,  30.,  40.],
       [100., 200., 300., 400.]])

In [16]:
b.dtype

dtype('float64')

In [17]:
b.ndim, b.shape, b.size

(2, (3, 4), 12)

In [19]:
np.zeros((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
# get ndarray from start to stop with 200 entries distributed evenly 
ab=np.linspace(0, 100, 200, dtype=np.float16)
ab

array([  0.    ,   0.5024,   1.005 ,   1.508 ,   2.01  ,   2.512 ,
         3.016 ,   3.518 ,   4.02  ,   4.523 ,   5.023 ,   5.527 ,
         6.03  ,   6.53  ,   7.035 ,   7.54  ,   8.04  ,   8.54  ,
         9.05  ,   9.55  ,  10.05  ,  10.555 ,  11.055 ,  11.555 ,
        12.06  ,  12.56  ,  13.06  ,  13.57  ,  14.07  ,  14.57  ,
        15.08  ,  15.58  ,  16.08  ,  16.58  ,  17.08  ,  17.6   ,
        18.1   ,  18.6   ,  19.1   ,  19.6   ,  20.1   ,  20.61  ,
        21.11  ,  21.61  ,  22.11  ,  22.61  ,  23.11  ,  23.62  ,
        24.12  ,  24.62  ,  25.12  ,  25.62  ,  26.12  ,  26.64  ,
        27.14  ,  27.64  ,  28.14  ,  28.64  ,  29.14  ,  29.64  ,
        30.16  ,  30.66  ,  31.16  ,  31.66  ,  32.16  ,  32.66  ,
        33.16  ,  33.66  ,  34.16  ,  34.7   ,  35.2   ,  35.7   ,
        36.2   ,  36.7   ,  37.2   ,  37.7   ,  38.2   ,  38.7   ,
        39.2   ,  39.7   ,  40.2   ,  40.72  ,  41.22  ,  41.72  ,
        42.22  ,  42.72  ,  43.22  ,  43.72  ,  44.22  ,  44.7

In [31]:
type(ab)

numpy.ndarray

In [33]:
# get ndarray from start to stop in arthmatic sequence with distance 0.5
np.arange(0, 100, 0.5, dtype=np.float16)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

## Standard Normal - mean 0 and standard deviation = 1

In [51]:
np.random.standard_normal(12)

array([ 0.13140902,  1.21588139, -0.96963943,  0.39310102,  0.18278402,
        0.1695414 ,  0.26330929,  2.9873208 ,  0.85438714,  1.73538556,
       -0.70155959, -0.86887342])

In [48]:
n = 100
sum = 0
for i in np.random.standard_normal(n):
    sum += i
sum/n

0.08543421414130037

## Standard Deviation

In [50]:
np.std(np.random.standard_normal(1000))

1.005323840589523

In [53]:
a = np.random.standard_normal((2,3))
a

array([[-1.87167475,  0.83604938,  0.10363229],
       [ 0.09646385,  0.59171575, -0.17908193]])

In [54]:
b = np.random.standard_normal((2,3))
b

array([[ 1.45227699, -1.02605063, -0.21577169],
       [ 0.10435501,  1.19083753,  1.11452954]])

In [58]:
# Veritcal Stack 
c = np.vstack([a,b])
c.ndim, c.shape, c.size

(2, (4, 3), 12)

In [59]:
# Horizonal Stack
d = np.hstack([[a,b]])
d.ndim, d.shape, d.size

(3, (2, 2, 3), 12)

In [62]:
e = c.transpose()
e.ndim, e.shape, e.size

(2, (3, 4), 12)

In [64]:
## Save Array to file
np.save('example.npy', e)

In [65]:
e1 = np.load('example.npy')

In [66]:
e1

array([[-1.87167475,  0.09646385,  1.45227699,  0.10435501],
       [ 0.83604938,  0.59171575, -1.02605063,  1.19083753],
       [ 0.10363229, -0.17908193, -0.21577169,  1.11452954]])