In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
v = np.linspace(1, 10, 5)

In [14]:
v[0]

1.0

In [4]:
vv = np.random.random((5,4))

In [11]:
vv

array([[0.08907513, 0.99760799, 0.96605896, 0.15612371],
       [0.09475734, 0.31712449, 0.80341632, 0.64559318],
       [0.73087458, 0.96970202, 0.19105279, 0.78264969],
       [0.43099627, 0.15105345, 0.18192711, 0.30926629],
       [0.94505404, 0.94521225, 0.70065321, 0.45449773]])

## NumPy indexing of 2D array [x,y]

In [12]:
vv[1,1]

0.3171244882904225

## Python indexing of 2D array [][]

In [13]:
ary = [[1,2,3],[4,5,6]]
ary[1][1]

5

In [15]:
# Slicing 1D array is similar to 1D array of python
v[2:4]

array([5.5 , 7.75])

## Use .copy to avoid change in value of original array

In [16]:
v

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
v3 = v[2:4]

In [28]:
v3

array([5.5 , 7.75])

In [29]:
v3[0] = 0

In [30]:
v3

array([0.  , 7.75])

In [32]:
# setting first element of v3 to 0 also caused value in v to change
v

array([ 1.  ,  3.25,  0.  ,  7.75, 10.  ])

### Use .copy

In [34]:
v4 = v[2:4].copy()

In [35]:
v4

array([0.  , 7.75])

In [36]:
v4[0] = 20

In [37]:
v4

array([20.  ,  7.75])

In [38]:
# See no change in v4 affected v
v

array([ 1.  ,  3.25,  0.  ,  7.75, 10.  ])

## Conditionaly Select specific elements of an array 

In [39]:
v[[1,2,3]]

array([3.25, 0.  , 7.75])

In [41]:
v[0] = -1

In [42]:
v > 0

array([False,  True, False,  True,  True])

In [43]:
bool_index = v>0
positive_v = v[bool_index].copy()

In [44]:
positive_v

array([ 3.25,  7.75, 10.  ])